# Generated by Django 3.2 on 2021-04-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comment_commentsection_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsection',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
